config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "about#index"
    get "/about", to: "about#index"

  resources :notes

  resources :candles

  devise_scope :user do      
       get '/users/sign_out' => 'devise/sessions#destroy'  
       post '/users/sign_out' => 'devise/sessions#destroy'   
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/candle.rb
class Candle < ApplicationRecord
    belongs_to :user
    validates :name, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: { maximum: 35 }
    validates :body, presence: true, length: { maximum: 610 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes
  has_many :candles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candles_controller.rb
class CandlesController < ApplicationController
  before_action :set_candle, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @candles = Candle.where(user_id: current_user.id)
  end

  def show
  end

  def new
    @candle = Candle.new
  end

  def edit
  end

  def create
    @candle = Candle.new(candle_params)
    @candle.user = current_user  

      if @candle.save
        enqueue_unlit_job if @candle.lit?
        redirect_to candles_url notice: "Candle created!"

      else
        render :new, status: :unprocessable_entity
      end
    end

  def update
      if @candle.update(candle_params)
        enqueue_unlit_job if @candle.lit?
        redirect_to candles_url, notice: "Candle updated."
      else
         render :edit, status: :unprocessable_entity
      end
    end

  def destroy
    @candle.destroy!
    redirect_to candles_url, notice: "Candle deleted."
  end

  private
  def set_candle
    @candle = Candle.find(params[:id])
  end

  def candle_params
    params.require(:candle).permit(:name, :lit)
  end
    
  def enqueue_unlit_job
    if @candle.persisted?
      CandleUnlitJob.set(wait: 24.hours).perform_later(@candle.id)
    else
      Rails.logger.warn "CandlesController: Attempted to enqueue job for unsaved candle."
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]
   before_action :authenticate_user!

  def index
    @notes = Note.all
  end

  def show
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = Note.new(note_params)
    @note.user = current_user     

    if @note.save
      redirect_to notes_url, notice: "Postcard created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
      if @note.update(note_params)
        redirect_to notes_url, notice: "Postcard updated."
      else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @note.destroy!
    redirect_to notes_url, notice: "Postcard deleted."
  end

  private
  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :body, :recipient)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candles_helper.rb
module CandlesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/about/index.html.erb
<% if user_signed_in? %>
<h2 class="base-text">About Us</h2>
<%= link_to "https://988lifeline.org", target: "_blank", class: "m-6 p-2 text-center rounded bg-amber-50 font-serif block no-underline hover:motion-safe:animate-pulse" do %>
  <div>
    If you or someone you know is struggling with thoughts of suicide, please call, text, or chat 988 for the Suicide and Crisis Lifeline.
  </div>
<% end %>

  <div class="bm-6 p-2 rounded bg-amber-50 text-center font-serif">
    <p>
      <strong>The mission of Memento Mori is to normalize grief.</strong> Even though grief is a universal human experience that will eventually impact us all (if it hasn't already), there are very few everday avenues to publicly express grief.
    </p>
      <i class="fa-solid fa-skull"></i>
    <p>
      In 2022, I lost my dad to suicide. Over night, I inadvertently became an advocate for suicide prevention, mental illness, and grief. While navigating my own grieving process, however, I often found that I felt uncomfortable expressing my grief around others. I longed for an avenue where I could freely express the weight of carrying such a massive loss with me every day. I wanted to know my grief <strong>mattered</strong> in the world.
    </p>
      <i class="fa-solid fa-fire-flame-curved"></i>
    <p>
      Over time, I noticed something interesting. The one place where I felt I could go to make my grief known was social media. In between the banal Instagram posts of sunsets, lattes, and #ootds, I would post notes addressed to my dead dad. Even though I'm fairly certain my dad isn't actually reading my posts, addressing captions to him met a very ancient impulse to commune with the departed. I began noticing notes addressed to dead loved ones across my social media feeds and realized we were all scratching that very same human itch. While funeral homes often have virutal obituary sites, activity tends to fall off by the time of the funeral and I found the cursive fonts and common imagery of angel wings and swans on placid lakes to be alienating and far from the actual lived experience of my grief. 
    </p>
      <i class="fa-solid fa-envelope"></i>
    <p class="font-extrabold">
      With Memento Mori, you can anonymously write postcards on our Postcards page to anyone who isn't here any longer and have your words displayed on our feed. On our Candles page, you can light virtual candles to honor the departed. Here, your grief will find community with others navigating the hard, never-ending work of missing those we love.
    </p>
  </div>
  
  <div class="text-sm font-serif bg-amber-50 text-center rounded m-6">
    <p class="p-1">
      Please note that any postcards containing racist, homophobic, misogynistic, transphobic, xenophobic, ableist, or otherwise abusive content will be removed. 
    </p>
    <p class="pb-1">
      Bigots will not be granted entry into our little corner of the Great Beyond. 
    </p>
  </div>
<% end %>

app/views/candles/edit.html.erb
<% if user_signed_in? %>
<h2 class="base-text">Editing Candle</h2>
<div class="m-4">
  <%= form_with model: @candle do |form| %>
  <div>
    <%= form.label :name, class: "base-text" %><br>
    <%= form.text_field :name, class: "bg-amber-50 rounded" %>
    <% @candle.errors.full_messages_for(:name).each do |message| %>
      <div class="error-text"><%= message %></div>
    <% end %>
  </div>

<div class="p-2">
    <%= form.check_box :lit, class: "bg-amber-50 hover:pointer-click" %>
    <%= form.label "light this candle?", class: "base-text inline ml-2" %>
    <% @candle.errors.full_messages_for(:lit).each do |message| %>
      <div class="error-text"><%= message %></div>
    <% end %>
  </div>
  
  <div>
    <%= form.submit "Update Candle", class: "button cursor-pointer" %>
      <i class="fa-solid fa-fire-flame-curved p-2 text-amber-50 text-2xl"></i>
  </div>
<% end %>
</div>
<% end %>

app/views/candles/index.html.erb
<% if user_signed_in? %>
<div class="w-full">
  <% content_for :title, "Candles" %>
  <div class="flex justify-between items-center mb-6">
    <h2 class="base-text">Candles</h2>
    <%= link_to new_candle_path, class: "button cursor-pointer flex items-center space-x-2" do %>
      <i class="fa-solid fa-fire-flame-curved"></i>
      <span>New Candle</span>
    <% end %>
  </div>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
    <% @candles.each do |candle| %>
      <div class="text-center">
        <%= link_to candle_path(candle), class: "block" do %>
          <%= render(CandleComponent.new(candle: candle)) %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/candles/new.html.erb
<% if user_signed_in? %>
<h2 class="base-text">New Candle</h2>
<div class="m-4">
  <%= form_with model: @candle do |form| %>
  <div>
    <%= form.label :name, "Create a candle for...", class: "base-text" %><br>
    <%= form.text_field :name, placeholder: "Name", class: "bg-amber-50 rounded" %>
    <% @candle.errors.full_messages_for(:name).each do |message| %>
      <div class="error-text"><%= message %></div>
    <% end %>
  </div>

  <div class="p-2">
    <%= form.check_box :lit, class: "bg-amber-50 hover:pointer-click" %>
    <%= form.label "light this candle?", class: "base-text inline ml-2" %>
    <% @candle.errors.full_messages_for(:lit).each do |message| %>
      <div class="error-text"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit "Create Candle", class: "button cursor-pointer" %>
     <i class="fa-solid fa-fire-flame-curved p-2 text-amber-50 text-2xl"></i>
  </div>
<% end %>
</div>
<% end %>

app/views/candles/show.html.erb
<% if user_signed_in? %>
<div class="mx-auto md:w-2/3 w-full flex relative">
  <div class="relative w-full">
    <%= button_to @candle, method: :delete, class: "absolute top-7 left-10 bg-red-800 px-2 rounded-3xl hover:text-red-800 text-amber-50 hover:bg-amber-50 z-10" do %>
      <i class="fa-solid fa-xmark text-sm"></i>
    <% end %>
    <%= render(CandleComponent.new(candle: @candle)) %>
    <div class="text-center mt-6"> 
      <%= link_to "Update this candle?", edit_candle_url(@candle), class: "button" %>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MementoMori</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-stone-900">
    <main class="container mx-auto px-5 prose">
     <%= image_tag("memento_mori.svg", :alt => "memento mori") %>
     <p class="base-text italic">Your postal service to the Great Beyond...</p>
        <%= render(NavigationComponent.new) do %>
        <% end %>
          <p class="notice error-text"><%= notice %></p>
       <p class="alert error-text"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/notes/index.html.erb
<% if user_signed_in? %>
  <div class="flex justify-between items-center mb-6">
    <h2 class="font-bold base-text">Postcards</h2>
    <%= link_to new_note_path, class: "button cursor-pointer flex items-center space-x-2", id: "new-note" do %>
      <i class="fa-solid fa-pencil"></i>
      <span>New Postcard</span>
    <% end %>
  </div>
  <% @notes.each do |note| %>
    <div class="p-2">
      <%= render(NoteComponent.new(note: note)) %>
    </div>
  <% end %>
<% end %>

app/views/notes/new.html.erb
<% if user_signed_in? %>
<h2 class="base-text">New Postcard</h2>
<div class="m-4">
  <p class="base-text"><strong class="base-text">*</strong> indicates required fields</p>
  <%= form_with model: @note do |form| %>
    <div>
      <%= form.label :recipient, class: "base-text"%><br>
      <%= form.text_field :recipient, class: "bg-amber-50 rounded" %>
      <% @note.errors.full_messages_for(:recipient).each do |message| %>
        <div class="error-text"><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :title, class: "base-text"%><strong class="base-text">*</strong><br>
      <%= form.text_field :title, class: "bg-amber-50 rounded", required: true %>
      <% @note.errors.full_messages_for(:title).each do |message| %>
        <div class="error-text"><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :body, class: "base-text" %><strong class="base-text">*</strong><br>
      <%= form.text_area :body, class: "bg-amber-50 rounded", required: true %><br>
      <% @note.errors.full_messages_for(:body).each do |message| %>
        <div class="error-text"><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.submit "Send Postcard", class: "button cursor-pointer" %>
      <i class="fa-regular fa-paper-plane p-2 text-amber-50 text-xl"></i>
    </div>
  <% end %>
</div>
<% end %>